image: node:latest

build:
  stage: build
  script:
    - npm install
    - npm run test
  tags:
    - docker

# test_db:
#   script:
#     - npm install
#     - node ./specs/start.js ./specs/db-postgres.spec.js
