

build:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run test
  tags:
    - docker
  only:
    - dev

# test_db:
#   script:
#     - npm install
#     - node ./specs/start.js ./specs/db-postgres.spec.js
